import { FC } from "react";
import Head from "next/head";
import Nav from "./nav";
import Footer from "./footer";

const Layout: FC = ({ children }) => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App With TW + TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      {children}
      <Footer />
    </div>
  );
};

export default Layout;
